wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719503301
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 23
      4: 3.12.2
      5: 0.17.1
      8:
      - 3
      - 5
      13: windows-amd64
